---
- name: Deploy App
  hosts: app
  become: true
  tasks:
    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/ubuntu/reddit
        version: monolith
        clone: yes
      notify: reload puma

#    - name: bundle install
#      shell:
#        cmd: bundle install
#        chdir: /home/ubuntu/reddit/
#      notify: reload puma

    - name: bundle install
      bundler:
        state: present
        chdir: /home/ubuntu/reddit

    - name: Start Puma
      systemd:
        name: puma
        state: started
        enabled: yes

  handlers:
    - name: reload puma
      become: true
      systemd: name=puma state=restarted
