#cloud-config
package_update: true
packages:
  - ruby-full
  - ruby-bundler
  - build-essential
  - mongodb
  - git

users:
  - name: yc-user
    groups: sudo
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: true
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDGqjzWZLip/pGTa1NrEIQPazCakfezQvDCFCD6+ctQDe5GKoKBcjdRj0bTuA1G9KWWZ85BpeE/aPo67L5HmsSAbKhWHlBeazKVEwYXjZC+8rOlS3nsbAxafu6ohKX/iBG8UXxEpyO2Gyr0S0a7lPMJx49Nm0FIsLIDdK6RxKLLb0hd0gC1vuuSVbvV6K5zNVH5tRw8JGkp9uIzLzS0mAdtFa7rirD2mErv9YEjAuPvC6GJBi6jY257dqq6woYxsYLhZhQVfJB6ilFp0uXBKAgROq8qWUug+3j1aOd4dJdtpJpMxniHagh+cke4zNSF6/vIufF95wLGp0d+fRMzyPT60BrTYwVenMnilH5b5PKV1400oaNuPOSapIGpt5eTTm+1Fk9RXZDSofNtqUaNS2aCAcMpv8DdgrkumrKV3tm4LCTkRP5qFWLW8AgxBbRsPYOTeJ3L3FE3YZrwcOFeYzLtJDo5QeE+vg3E5ijwSI+ysEtA0rRqfc7UOt9tuiT+enU= appuser

runcmd:
  - sudo systemctl start mongodb
  - sudo systemctl enable mongodb
  - sudo cd /home/yc-user
  - git clone -b monolith https://github.com/express42/reddit.git
  - cd /home/yc-user/reddit
  - bundle install
  - puma -d
